CREATE DATABASE db_seguradora;
USE db_seguradora;

CREATE TABLE ADMINISTRADORES(
	ADM_ID INT NOT NULL auto_increment,
    ADM_NOME VARCHAR(50),
    ADM_USERNAME VARCHAR(50),
    ADM_SENHA VARCHAR(255),
    
    CONSTRAINT ADM_PK PRIMARY KEY (ADM_ID)
);

CREATE TABLE CARROS(
	CAR_ID INT NOT NULL auto_increment,
    CAR_PLACA varchar(7) NOT NULL,
	CAR_MARCA varchar(50) NOT NULL,
	CAR_MODELO varchar(50) NOT NULL,
	CAR_ANO varchar(4) NOT NULL,
    
    CONSTRAINT CAR_PK PRIMARY KEY (CAR_ID)
)