CREATE DATABASE CONSULTORIO;

USE CONSULTORIO;
 
CREATE TABLE ADMINISTRADOR(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USUARIO VARCHAR(50) NOT NULL,
	SENHA VARCHAR(255) NOT NULL
);
CREATE TABLE MEDICO(
      ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
      NOME VARCHAR(50) NOT NULL,
      ESPECIALIDADE VARCHAR(50) NOT NULL
);
CREATE TABLE IMAGEM(
	ID INT NOT NULL primary KEY auto_increment,
    PATH VARCHAR(255) NOT NULL
);


CREATE TABLE PACIENTE(
       ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
       NOME VARCHAR(50) NOT NULL,
       DATA_NASCIMENTO DATE NOT NULL,
       ID_IMAGEM INT,
       TIPO_SANGUINEO ENUM ("A+", "A-", "AB+", "AB-", "B+", "B-", "O+", "O-") NOT NULL,
       
       FOREIGN KEY (ID_IMAGEM) REFERENCES IMAGEM(ID) ON DELETE SET NULL
);

CREATE TABLE CONSULTA(
       ID_CON INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
       ID_MEDICO INT NOT NULL,
       ID_PACIENTE INT NOT NULL,
       DATA_CONSULTA DATE NOT NULL,
       HORA_CONSULTA TIME NOT NULL,
       OBSERVACAO VARCHAR(255),

       FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID) ON DELETE CASCADE,
       FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID) ON DELETE CASCADE
);